CREATE TABLE business_sequence(
  prefix TEXT NOT NULL,
  utc_day BIGINT NOT NULL,
  value BIGINT NOT NULL CHECK(value > 0),
  PRIMARY KEY(prefix, utc_day)
);

CREATE TABLE idempotency_record(
  scope TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  request_digest TEXT NOT NULL,
  result_status INTEGER,
  result_content_type TEXT,
  result_body TEXT,
  expires_at BIGINT NOT NULL,
  lease_expires_at BIGINT NOT NULL,
  lease_token TEXT NOT NULL,
  permanent SMALLINT NOT NULL CHECK(permanent IN (0, 1)),
  PRIMARY KEY(scope, idempotency_key)
);

CREATE TABLE user_account(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  phone TEXT NOT NULL UNIQUE,
  nickname TEXT NOT NULL,
  status SMALLINT NOT NULL CHECK(status IN (0, 1)),
  registered_at BIGINT NOT NULL,
  balance_cent BIGINT NOT NULL DEFAULT 0 CHECK(balance_cent >= 0),
  debt_cent BIGINT NOT NULL DEFAULT 0 CHECK(debt_cent >= 0),
  has_active_flow SMALLINT NOT NULL DEFAULT 0 CHECK(has_active_flow IN (0, 1)),
  version BIGINT NOT NULL DEFAULT 1 CHECK(version > 0),
  deleted SMALLINT NOT NULL DEFAULT 0 CHECK(deleted IN (0, 1))
);

CREATE TABLE user_credential(
  user_id BIGINT PRIMARY KEY REFERENCES user_account(id) ON DELETE CASCADE,
  password_hash TEXT NOT NULL
);

CREATE TABLE user_avatar(
  user_id BIGINT PRIMARY KEY REFERENCES user_account(id) ON DELETE CASCADE,
  data BYTEA NOT NULL,
  content_type TEXT NOT NULL,
  etag TEXT NOT NULL
);

CREATE TABLE wallet_account(
  user_id BIGINT PRIMARY KEY REFERENCES user_account(id),
  balance_cent BIGINT NOT NULL CHECK(balance_cent >= 0),
  debt_cent BIGINT NOT NULL CHECK(debt_cent >= 0),
  version BIGINT NOT NULL CHECK(version > 0),
  updated_at BIGINT NOT NULL
);

CREATE TABLE wallet_transaction(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES user_account(id),
  transaction_no TEXT NOT NULL UNIQUE,
  type SMALLINT NOT NULL CHECK(type IN (0, 1, 2)),
  amount_cent BIGINT NOT NULL,
  balance_after_cent BIGINT NOT NULL,
  debt_after_cent BIGINT NOT NULL,
  related_no TEXT NOT NULL,
  created_at BIGINT NOT NULL
);

CREATE TABLE recharge_order(
  recharge_no TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES user_account(id),
  requested_cent BIGINT NOT NULL,
  debt_paid_cent BIGINT NOT NULL,
  balance_added_cent BIGINT NOT NULL,
  balance_after_cent BIGINT NOT NULL,
  debt_after_cent BIGINT NOT NULL,
  completed_at BIGINT NOT NULL
);

CREATE TABLE station(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  adcode TEXT NOT NULL,
  latitude_e6 BIGINT NOT NULL,
  longitude_e6 BIGINT NOT NULL,
  business_hours TEXT NOT NULL,
  enabled SMALLINT NOT NULL CHECK(enabled IN (0, 1))
);

CREATE TABLE charger(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  station_id BIGINT NOT NULL REFERENCES station(id),
  code TEXT NOT NULL UNIQUE,
  charger_type SMALLINT NOT NULL CHECK(charger_type IN (0, 1)),
  power_watt BIGINT NOT NULL CHECK(power_watt > 0),
  connector_standard TEXT NOT NULL,
  status SMALLINT NOT NULL CHECK(status IN (0, 1, 2, 3)),
  total_count BIGINT NOT NULL DEFAULT 0,
  total_minutes BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE region_tariff(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  adcode TEXT NOT NULL,
  electricity_cent_per_kwh INTEGER NOT NULL,
  service_cent_per_kwh INTEGER NOT NULL,
  effective_from BIGINT NOT NULL,
  effective_to BIGINT NOT NULL,
  UNIQUE(adcode, effective_from)
);

CREATE TABLE charging_flow(
  flow_no TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES user_account(id),
  station_id BIGINT NOT NULL REFERENCES station(id),
  charger_type SMALLINT NOT NULL CHECK(charger_type IN (0, 1)),
  charger_id BIGINT REFERENCES charger(id),
  charger_code TEXT,
  status INTEGER NOT NULL CHECK(status IN (10, 20, 30, 40, 50, 60, 70, 80, 90)),
  quote_no TEXT UNIQUE,
  quote_charger_id BIGINT,
  quote_charger_code TEXT,
  electricity_price INTEGER,
  base_service_price INTEGER,
  queue_adjustment_bp INTEGER,
  ml_adjustment_bp INTEGER,
  final_service_price INTEGER,
  total_price INTEGER,
  quote_expires_at BIGINT,
  reserved_until BIGINT,
  started_at BIGINT,
  version BIGINT NOT NULL CHECK(version > 0),
  created_at BIGINT NOT NULL
);

CREATE UNIQUE INDEX uq_active_flow_user ON charging_flow(user_id)
  WHERE status IN (10, 20, 30, 40, 50, 80);
CREATE UNIQUE INDEX uq_active_flow_charger ON charging_flow(charger_id)
  WHERE charger_id IS NOT NULL AND status IN (20, 30, 40, 50, 80);

CREATE TABLE flow_event(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  flow_no TEXT NOT NULL REFERENCES charging_flow(flow_no),
  from_status INTEGER NOT NULL,
  to_status INTEGER NOT NULL,
  reason_code TEXT NOT NULL,
  at BIGINT NOT NULL
);

CREATE TABLE outbox_event(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  aggregate_type TEXT NOT NULL,
  aggregate_id TEXT NOT NULL,
  from_status INTEGER NOT NULL,
  to_status INTEGER NOT NULL,
  reason_code TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  delivery_status SMALLINT NOT NULL DEFAULT 0 CHECK(delivery_status IN (0, 1, 2)),
  delivery_attempts INTEGER NOT NULL DEFAULT 0 CHECK(delivery_attempts >= 0),
  available_at BIGINT NOT NULL,
  published_at BIGINT
);
CREATE INDEX ix_outbox_delivery ON outbox_event(delivery_status, available_at, id);

CREATE TABLE flow_queue(
  station_id BIGINT NOT NULL REFERENCES station(id),
  charger_type SMALLINT NOT NULL,
  flow_no TEXT NOT NULL UNIQUE REFERENCES charging_flow(flow_no),
  sequence BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
);

CREATE TABLE charging_order(
  order_no TEXT PRIMARY KEY,
  flow_no TEXT NOT NULL UNIQUE REFERENCES charging_flow(flow_no),
  user_id BIGINT NOT NULL REFERENCES user_account(id),
  station_id BIGINT NOT NULL REFERENCES station(id),
  station_name TEXT NOT NULL,
  charger_id BIGINT NOT NULL REFERENCES charger(id),
  charger_code TEXT NOT NULL,
  charger_type SMALLINT NOT NULL,
  electricity_price INTEGER NOT NULL,
  service_price INTEGER NOT NULL,
  power_watt BIGINT NOT NULL,
  time_scale INTEGER NOT NULL,
  target_amount_cent BIGINT,
  status INTEGER NOT NULL CHECK(status IN (30, 40, 50, 60, 70, 80, 90)),
  created_at BIGINT NOT NULL,
  started_at BIGINT,
  ended_at BIGINT,
  energy_mwh BIGINT NOT NULL DEFAULT 0,
  amount_cent BIGINT NOT NULL DEFAULT 0,
  paid_cent BIGINT NOT NULL DEFAULT 0,
  debt_added_cent BIGINT NOT NULL DEFAULT 0,
  balance_after_cent BIGINT NOT NULL DEFAULT 0,
  debt_after_cent BIGINT NOT NULL DEFAULT 0,
  settled_at BIGINT
);

INSERT INTO station(id, code, name, address, adcode, latitude_e6, longitude_e6,
                    business_hours, enabled) VALUES
 (1, 'ZGC', 'NCS 中关村充电站', '北京市海淀区中关村大街 27 号', '110108', 39977680, 116316417, '00:00-24:00', 1),
 (2, 'XEQ', 'NCS 西二旗充电站', '北京市海淀区上地信息路 2 号', '110108', 40052768, 116307517, '00:00-24:00', 1),
 (3, 'CBD', 'NCS 国贸充电站', '北京市朝阳区建国门外大街 1 号', '110105', 39908372, 116457658, '00:00-24:00', 1)
ON CONFLICT (id) DO NOTHING;

INSERT INTO region_tariff(adcode, electricity_cent_per_kwh, service_cent_per_kwh,
                          effective_from, effective_to) VALUES
 ('110108', 85, 50, 0, 4102444800), ('110105', 92, 48, 0, 4102444800)
ON CONFLICT (adcode, effective_from) DO NOTHING;

INSERT INTO charger(id, station_id, code, charger_type, power_watt, connector_standard,
                    status, total_count, total_minutes) VALUES
 (1, 1, 'ZGC-DC-01', 1, 60000, 'GB/T', 0, 0, 0),
 (2, 1, 'ZGC-DC-02', 1, 60000, 'GB/T', 0, 0, 0),
 (3, 1, 'ZGC-DC-03', 1, 120000, 'GB/T', 0, 0, 0),
 (4, 1, 'ZGC-AC-01', 0, 7000, 'GB/T', 0, 0, 0),
 (5, 1, 'ZGC-AC-02', 0, 7000, 'GB/T', 0, 0, 0),
 (6, 2, 'XEQ-DC-01', 1, 120000, 'GB/T', 0, 0, 0),
 (7, 2, 'XEQ-AC-01', 0, 7000, 'GB/T', 0, 0, 0),
 (8, 3, 'CBD-DC-01', 1, 60000, 'GB/T', 2, 0, 0),
 (9, 3, 'CBD-AC-01', 0, 7000, 'GB/T', 0, 0, 0)
ON CONFLICT (id) DO NOTHING;
