ALTER TABLE station ADD COLUMN version BIGINT NOT NULL DEFAULT 1 CHECK(version > 0);
ALTER TABLE charger ADD COLUMN version BIGINT NOT NULL DEFAULT 1 CHECK(version > 0);

CREATE TABLE admin_account(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  status SMALLINT NOT NULL CHECK(status IN (0, 1)),
  must_change_password SMALLINT NOT NULL DEFAULT 0 CHECK(must_change_password IN (0, 1)),
  version BIGINT NOT NULL DEFAULT 1 CHECK(version > 0)
);
CREATE TABLE admin_role(
  admin_id BIGINT NOT NULL REFERENCES admin_account(id) ON DELETE CASCADE,
  role TEXT NOT NULL CHECK(role IN ('OPERATOR', 'OWNER', 'VIEWER')),
  PRIMARY KEY(admin_id, role)
);
CREATE TABLE ops_log(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_admin_id BIGINT NOT NULL REFERENCES admin_account(id),
  action TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id TEXT NOT NULL,
  reason TEXT NOT NULL,
  at BIGINT NOT NULL
);
CREATE INDEX ix_ops_log_query ON ops_log(at DESC, actor_admin_id, action);

CREATE TABLE price_adjustment(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  station_id BIGINT NOT NULL REFERENCES station(id),
  charger_type SMALLINT NOT NULL CHECK(charger_type IN (0, 1)),
  source TEXT NOT NULL CHECK(source IN ('ML_APPROVED', 'MANUAL')),
  adjustment_bp INTEGER NOT NULL CHECK(adjustment_bp BETWEEN -2000 AND 2000),
  effective_from BIGINT NOT NULL,
  effective_to BIGINT NOT NULL,
  reason TEXT NOT NULL,
  CHECK(effective_to > effective_from)
);
CREATE INDEX ix_price_adjustment_effective
  ON price_adjustment(station_id, charger_type, effective_from, effective_to, id DESC);

CREATE TABLE device_command(
  command_no TEXT PRIMARY KEY,
  charger_id BIGINT NOT NULL REFERENCES charger(id),
  charger_code TEXT NOT NULL,
  status TEXT NOT NULL CHECK(status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED')),
  reason TEXT NOT NULL,
  actor_id TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  execute_at BIGINT NOT NULL,
  completed_at BIGINT,
  error_summary TEXT NOT NULL DEFAULT ''
);
CREATE INDEX ix_device_command_due ON device_command(status, execute_at);

CREATE TABLE ml_task(
  task_no TEXT PRIMARY KEY,
  task_type TEXT NOT NULL CHECK(task_type IN ('TRAIN', 'PREDICT')),
  status TEXT NOT NULL CHECK(status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'TIMED_OUT')),
  model_version TEXT NOT NULL DEFAULT '',
  horizon_hours TEXT NOT NULL DEFAULT '',
  created_at BIGINT NOT NULL,
  finished_at BIGINT,
  metrics_summary TEXT NOT NULL DEFAULT '',
  error_summary TEXT NOT NULL DEFAULT ''
);
CREATE INDEX ix_ml_task_running ON ml_task(task_type, status, created_at DESC);

CREATE TABLE backup_record(
  backup_no TEXT PRIMARY KEY,
  status TEXT NOT NULL,
  checksum TEXT NOT NULL DEFAULT '',
  size_bytes BIGINT NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL,
  verification_status TEXT NOT NULL DEFAULT '',
  verified_at BIGINT,
  storage_path TEXT NOT NULL DEFAULT ''
);
